### ISSUE TITLE
delete ntpdate

### ISSUE THREAD

**Issue by le9i0nx** [debops/ansible-ntp#32]
I use to monitor command
ntpdate -q pool.ntp.org
https://github.com/debops/ansible-ntp/blob/master/tasks/install.yml#L3
I can't influence the removal ntpdate

**Comment by drybjed** [comment]
The Debian `ntpdate` package provides `ntpdate-debian` script which is run every time a network interface is brought up. This might disrupt the host time tracking, when the time jumps backwards - that's why DebOps uses `openntpd` by default.

If you're fine with this, then I suppose that I could add a boolean variable that disables automatic removal of `ntpdate` package, that way you can install it for example via `debops.apt_install` role.

**Comment by drybjed** [comment]
@le9i0nx The variable has been added in the current `master`, can you check if everything works correctly now?

**Comment by le9i0nx** [comment]
Thanks as I need
